// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Models;

#nullable disable

namespace rest.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20260406031749_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("AssetVersionAssets", b =>
                {
                    b.Property<int>("AssetVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressableAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetVersionId", "AddressableAssetId");

                    b.HasIndex("AddressableAssetId");

                    b.ToTable("asset_version_assets", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AddressableAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .HasDatabaseName("IX_AddressableAsset_Label");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("UQ_AddressableAsset_Path");

                    b.ToTable("addressable_assets", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("app_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AssetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("asset_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Catalog", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uuid");

                    b.HasIndex("KeyCode")
                        .IsUnique();

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique();

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("MyApi.Models.CatalogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyApi.Models.CatalogSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Prefix")
                        .IsUnique()
                        .HasDatabaseName("UQ_CatalogSeries_Category_Prefix");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MyApi.Models.CatalogVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayfabCatalogVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapShot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PlayfabCatalogVersion", "Major", "Minor", "Patch")
                        .IsUnique()
                        .HasDatabaseName("UQ_CatalogVersion_SemVer");

                    b.ToTable("catalog_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialLimitedEditionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsConsumableByCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsumableByTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitedEdition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStackable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTradable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(99);

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealCurrencyPrices")
                        .HasColumnType("jsonb");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int?>("UsagePeriodSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VirtualCurrencyPrices")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_Consumable_CurrentVersion")
                        .HasFilter("\"IsCurrentVersion\" = TRUE");

                    b.HasIndex("IsCurrentVersion");

                    b.HasIndex("Status");

                    b.HasIndex("CatalogUuid", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UQ_Consumable_Catalog_Revision");

                    b.ToTable("consumable_items", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.DropItem", b =>
                {
                    b.Property<int>("DropTableId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("DropTableId", "CatalogUuid");

                    b.HasIndex("CatalogUuid");

                    b.ToTable("drop_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_DropTableItem_PositiveWeight", "\"Weight\" > 0");

                            t.HasCheckConstraint("CK_DropTableItem_QuantityRange", "\"MinQuantity\" <= \"MaxQuantity\"");
                        });
                });

            modelBuilder.Entity("MyApi.Models.DropTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyCode")
                        .IsUnique();

                    b.ToTable("drop_tables", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DropTableId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid");

                    b.HasIndex("DropTableId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("MyApi.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialLimitedEditionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitedEdition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTradable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealCurrencyPrices")
                        .HasColumnType("jsonb");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VirtualCurrencyPrices")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipment_CurrentVersion")
                        .HasFilter("\"IsCurrentVersion\" = TRUE");

                    b.HasIndex("IsCurrentVersion");

                    b.HasIndex("Status");

                    b.HasIndex("CatalogUuid", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipment_Catalog_Revision");

                    b.ToTable("equipment_items", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.ExpTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logic")
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(99);

                    b.Property<int>("MinLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("exp_tables", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleCostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenCostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid");

                    b.HasIndex("SingleCostId");

                    b.HasIndex("TenCostId");

                    b.ToTable("Lotteries");
                });

            modelBuilder.Entity("MyApi.Models.LotteryPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotteryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid");

                    b.HasIndex("LotteryId", "Rarity");

                    b.ToTable("lottery_prizes", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.LotteryRarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotteryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LotteryId");

                    b.ToTable("lottery_rarities", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpTableId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid");

                    b.HasIndex("ExpTableId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MyApi.Models.VirtualCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUuid");

                    b.ToTable("VirtualCurrencies");
                });

            modelBuilder.Entity("AssetVersionAssets", b =>
                {
                    b.HasOne("MyApi.Models.AddressableAsset", null)
                        .WithMany()
                        .HasForeignKey("AddressableAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.AssetVersion", null)
                        .WithMany()
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Models.Catalog", b =>
                {
                    b.HasOne("MyApi.Models.CatalogSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MyApi.Models.CatalogSeries", b =>
                {
                    b.HasOne("MyApi.Models.CatalogCategory", "Category")
                        .WithMany("Series")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApi.Models.ConsumableItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.DropItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DropTable", "DropTable")
                        .WithMany("DropItems")
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("DropTable");
                });

            modelBuilder.Entity("MyApi.Models.Enemy", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DropTable", "DropTable")
                        .WithMany()
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("DropTable");
                });

            modelBuilder.Entity("MyApi.Models.EquipmentItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.VirtualCurrency", "SingleCost")
                        .WithMany()
                        .HasForeignKey("SingleCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.VirtualCurrency", "TenCost")
                        .WithMany()
                        .HasForeignKey("TenCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("SingleCost");

                    b.Navigation("TenCost");
                });

            modelBuilder.Entity("MyApi.Models.LotteryPrize", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Lottery", "Lottery")
                        .WithMany("Prizes")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("MyApi.Models.LotteryRarity", b =>
                {
                    b.HasOne("MyApi.Models.Lottery", "Lottery")
                        .WithMany("Rarities")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("MyApi.Models.Player", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.ExpTable", "ExpTable")
                        .WithMany("Players")
                        .HasForeignKey("ExpTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("ExpTable");
                });

            modelBuilder.Entity("MyApi.Models.VirtualCurrency", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.CatalogCategory", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("MyApi.Models.DropTable", b =>
                {
                    b.Navigation("DropItems");
                });

            modelBuilder.Entity("MyApi.Models.ExpTable", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("Rarities");
                });
#pragma warning restore 612, 618
        }
    }
}
