// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Models;

#nullable disable

namespace rest.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20260410130445_AddShop")]
    partial class AddShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("AssetVersionAssets", b =>
                {
                    b.Property<int>("AssetVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressableAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetVersionId", "AddressableAssetId");

                    b.HasIndex("AddressableAssetId");

                    b.ToTable("asset_version_assets", (string)null);
                });

            modelBuilder.Entity("DagDagNode", b =>
                {
                    b.Property<int>("DagsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootNodesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DagsId", "RootNodesId");

                    b.HasIndex("RootNodesId");

                    b.ToTable("DagDagNode");
                });

            modelBuilder.Entity("DagNodeDagNode", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("DagNodeDagNode");
                });

            modelBuilder.Entity("MyApi.Models.AchievementTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredProgress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("achievement_tiers", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AddressableAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .HasDatabaseName("IX_AddressableAsset_Label");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("UQ_AddressableAsset_Path");

                    b.ToTable("addressable_assets", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "Major", "Minor", "Patch")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppVersion_Platform_SemVer");

                    b.ToTable("app_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.AssetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Major", "Minor", "Patch")
                        .IsUnique()
                        .HasDatabaseName("UQ_AssetVersion_SemVer");

                    b.ToTable("asset_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.BundledItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementTierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int?>("RewardDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementTierId");

                    b.HasIndex("CatalogId");

                    b.HasIndex("RewardDefinitionId");

                    b.ToTable("bundled_items", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_Catalog_Uuid");

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique();

                    b.ToTable("catalogs", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.CatalogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("catalog_categories", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.CatalogSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Prefix")
                        .IsUnique()
                        .HasDatabaseName("UQ_CatalogSeries_Category_Prefix");

                    b.ToTable("catalog_series", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.CatalogVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Patch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapShot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Major", "Minor", "Patch")
                        .IsUnique()
                        .HasDatabaseName("UQ_CatalogVersion_SemVer");

                    b.ToTable("catalog_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialLimitedEditionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsConsumableByCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsumableByTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitedEdition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStackable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTradable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(99);

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int?>("UsagePeriodSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("CatalogUuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_Consumable_CurrentVersion")
                        .HasFilter("\"IsCurrentVersion\" = TRUE");

                    b.HasIndex("IsCurrentVersion");

                    b.HasIndex("Status");

                    b.HasIndex("CatalogUuid", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UQ_Consumable_Catalog_Revision");

                    b.ToTable("consumable_items", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Dag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DagType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dags", (string)null);

                    b.HasDiscriminator<string>("DagType").HasValue("Dag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyApi.Models.DagEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DagId");

                    b.HasIndex("ParentId", "ChildId", "DagId")
                        .IsUnique();

                    b.ToTable("DagEdges", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.DagMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("DagId", "NodeId")
                        .IsUnique();

                    b.ToTable("DagMemberships", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.DagNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DagId");

                    b.ToTable("DagNodes", (string)null);

                    b.HasDiscriminator<string>("NodeType").HasValue("DagNode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyApi.Models.DropItem", b =>
                {
                    b.Property<int>("DropTableId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("DropTableId", "CatalogUuid");

                    b.HasIndex("CatalogUuid");

                    b.ToTable("drop_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_DropTableItem_PositiveWeight", "\"Weight\" > 0");

                            t.HasCheckConstraint("CK_DropTableItem_QuantityRange", "\"MinQuantity\" <= \"MaxQuantity\"");
                        });
                });

            modelBuilder.Entity("MyApi.Models.DropTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyCode")
                        .IsUnique();

                    b.ToTable("drop_tables", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.EligibilityCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("eligibility_conditions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DropTableId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("DropTableId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("MyApi.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialLimitedEditionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitedEdition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTradable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("CatalogUuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipment_CurrentVersion")
                        .HasFilter("\"IsCurrentVersion\" = TRUE");

                    b.HasIndex("IsCurrentVersion");

                    b.HasIndex("Status");

                    b.HasIndex("CatalogUuid", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipment_Catalog_Revision");

                    b.ToTable("equipment_items", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.ExpTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logic")
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(99);

                    b.Property<int>("MinLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("exp_tables", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleCostAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleCostCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenCostAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenCostCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("SingleCostCurrencyId");

                    b.HasIndex("TenCostCurrencyId");

                    b.ToTable("Lotteries");
                });

            modelBuilder.Entity("MyApi.Models.LotteryPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("LotteryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrizeCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("LotteryId");

                    b.HasIndex("PrizeCatalogId");

                    b.ToTable("LotteryPrizes");
                });

            modelBuilder.Entity("MyApi.Models.LotteryRarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("LotteryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("LotteryId");

                    b.ToTable("LotteryRarities");
                });

            modelBuilder.Entity("MyApi.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialLimitedEditionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitedEdition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("MyApi.Models.ObjectiveCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("objective_criteria", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpTableId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("ExpTableId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MyApi.Models.RewardDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("reward_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("reward_definitions", (string)null);

                    b.HasDiscriminator<string>("reward_type").HasValue("RewardDefinition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyApi.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayFabItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItem");
                });

            modelBuilder.Entity("MyApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("MyApi.Models.UpdateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AssetVersionId");

                    b.HasIndex("AppVersionId", "AssetVersionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UpdateVersion_App_Asset");

                    b.ToTable("update_versions", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.VirtualCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2000000000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RechargeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("virtual_currencies", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.SkillTree", b =>
                {
                    b.HasBaseType("MyApi.Models.Dag");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasDiscriminator().HasValue("SkillTree");
                });

            modelBuilder.Entity("MyApi.Models.SkillNode", b =>
                {
                    b.HasBaseType("MyApi.Models.DagNode");

                    b.Property<int>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SkillId");

                    b.HasDiscriminator().HasValue("SkillNode");
                });

            modelBuilder.Entity("MyApi.Models.Achievement", b =>
                {
                    b.HasBaseType("MyApi.Models.RewardDefinition");

                    b.Property<int?>("EligibilityConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectiveCriteriaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("EligibilityConditionId")
                        .IsUnique();

                    b.HasIndex("ObjectiveCriteriaId")
                        .IsUnique();

                    b.ToTable("reward_definitions", t =>
                        {
                            t.Property("EligibilityConditionId")
                                .HasColumnName("Achievement_EligibilityConditionId");

                            t.Property("ObjectiveCriteriaId")
                                .HasColumnName("Achievement_ObjectiveCriteriaId");
                        });

                    b.HasDiscriminator().HasValue("Achievement");
                });

            modelBuilder.Entity("MyApi.Models.DailyMission", b =>
                {
                    b.HasBaseType("MyApi.Models.RewardDefinition");

                    b.Property<int?>("EligibilityConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectiveCriteriaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("EligibilityConditionId")
                        .IsUnique();

                    b.HasIndex("ObjectiveCriteriaId")
                        .IsUnique();

                    b.ToTable("reward_definitions", t =>
                        {
                            t.Property("EligibilityConditionId")
                                .HasColumnName("DailyMission_EligibilityConditionId");
                        });

                    b.HasDiscriminator().HasValue("DailyMission");
                });

            modelBuilder.Entity("MyApi.Models.LoginBonus", b =>
                {
                    b.HasBaseType("MyApi.Models.RewardDefinition");

                    b.Property<int?>("EligibilityConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredConsecutiveDays")
                        .HasColumnType("INTEGER");

                    b.HasIndex("EligibilityConditionId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LoginBonus");
                });

            modelBuilder.Entity("AssetVersionAssets", b =>
                {
                    b.HasOne("MyApi.Models.AddressableAsset", null)
                        .WithMany()
                        .HasForeignKey("AddressableAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.AssetVersion", null)
                        .WithMany()
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DagDagNode", b =>
                {
                    b.HasOne("MyApi.Models.Dag", null)
                        .WithMany()
                        .HasForeignKey("DagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DagNode", null)
                        .WithMany()
                        .HasForeignKey("RootNodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DagNodeDagNode", b =>
                {
                    b.HasOne("MyApi.Models.DagNode", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DagNode", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Models.AchievementTier", b =>
                {
                    b.HasOne("MyApi.Models.Achievement", null)
                        .WithMany("Tiers")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyApi.Models.BundledItem", b =>
                {
                    b.HasOne("MyApi.Models.AchievementTier", null)
                        .WithMany("BundledItems")
                        .HasForeignKey("AchievementTierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.RewardDefinition", null)
                        .WithMany("BundledItems")
                        .HasForeignKey("RewardDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.Catalog", b =>
                {
                    b.HasOne("MyApi.Models.CatalogSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MyApi.Models.CatalogSeries", b =>
                {
                    b.HasOne("MyApi.Models.CatalogCategory", "Category")
                        .WithMany("Series")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApi.Models.ConsumableItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.DagEdge", b =>
                {
                    b.HasOne("MyApi.Models.DagNode", "Child")
                        .WithMany("ParentEdges")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Dag", "Dag")
                        .WithMany()
                        .HasForeignKey("DagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyApi.Models.DagNode", "Parent")
                        .WithMany("ChildEdges")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Dag");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyApi.Models.DagMembership", b =>
                {
                    b.HasOne("MyApi.Models.Dag", "Dag")
                        .WithMany("Memberships")
                        .HasForeignKey("DagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DagNode", "Node")
                        .WithMany("Memberships")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dag");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("MyApi.Models.DagNode", b =>
                {
                    b.HasOne("MyApi.Models.Dag", null)
                        .WithMany("Nodes")
                        .HasForeignKey("DagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyApi.Models.DropItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogUuid")
                        .HasPrincipalKey("Uuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DropTable", "DropTable")
                        .WithMany("DropItems")
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("DropTable");
                });

            modelBuilder.Entity("MyApi.Models.Enemy", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.DropTable", "DropTable")
                        .WithMany()
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("DropTable");
                });

            modelBuilder.Entity("MyApi.Models.EquipmentItem", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.VirtualCurrency", "SingleCostCurrency")
                        .WithMany()
                        .HasForeignKey("SingleCostCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.VirtualCurrency", "TenCostCurrency")
                        .WithMany()
                        .HasForeignKey("TenCostCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("SingleCostCurrency");

                    b.Navigation("TenCostCurrency");
                });

            modelBuilder.Entity("MyApi.Models.LotteryPrize", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Lottery", "Lottery")
                        .WithMany("Prizes")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Catalog", "PrizeCatalog")
                        .WithMany()
                        .HasForeignKey("PrizeCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Lottery");

                    b.Navigation("PrizeCatalog");
                });

            modelBuilder.Entity("MyApi.Models.LotteryRarity", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Lottery", "Lottery")
                        .WithMany("Rarities")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Lottery");
                });

            modelBuilder.Entity("MyApi.Models.Material", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.Player", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.ExpTable", "ExpTable")
                        .WithMany("Players")
                        .HasForeignKey("ExpTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("ExpTable");
                });

            modelBuilder.Entity("MyApi.Models.Title", b =>
                {
                    b.HasOne("MyApi.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MyApi.Models.UpdateVersion", b =>
                {
                    b.HasOne("MyApi.Models.AppVersion", "App")
                        .WithMany()
                        .HasForeignKey("AppVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.AssetVersion", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("MyApi.Models.SkillNode", b =>
                {
                    b.HasOne("MyApi.Models.Skill", "Skill")
                        .WithMany("Nodes")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MyApi.Models.Achievement", b =>
                {
                    b.HasOne("MyApi.Models.EligibilityCondition", "EligibilityCondition")
                        .WithOne()
                        .HasForeignKey("MyApi.Models.Achievement", "EligibilityConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApi.Models.ObjectiveCriteria", "Objective")
                        .WithOne()
                        .HasForeignKey("MyApi.Models.Achievement", "ObjectiveCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EligibilityCondition");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("MyApi.Models.DailyMission", b =>
                {
                    b.HasOne("MyApi.Models.EligibilityCondition", "EligibilityCondition")
                        .WithOne()
                        .HasForeignKey("MyApi.Models.DailyMission", "EligibilityConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApi.Models.ObjectiveCriteria", "Objective")
                        .WithOne()
                        .HasForeignKey("MyApi.Models.DailyMission", "ObjectiveCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EligibilityCondition");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("MyApi.Models.LoginBonus", b =>
                {
                    b.HasOne("MyApi.Models.EligibilityCondition", "EligibilityCondition")
                        .WithOne()
                        .HasForeignKey("MyApi.Models.LoginBonus", "EligibilityConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EligibilityCondition");
                });

            modelBuilder.Entity("MyApi.Models.AchievementTier", b =>
                {
                    b.Navigation("BundledItems");
                });

            modelBuilder.Entity("MyApi.Models.CatalogCategory", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("MyApi.Models.Dag", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("MyApi.Models.DagNode", b =>
                {
                    b.Navigation("ChildEdges");

                    b.Navigation("Memberships");

                    b.Navigation("ParentEdges");
                });

            modelBuilder.Entity("MyApi.Models.DropTable", b =>
                {
                    b.Navigation("DropItems");
                });

            modelBuilder.Entity("MyApi.Models.ExpTable", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MyApi.Models.Lottery", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("Rarities");
                });

            modelBuilder.Entity("MyApi.Models.RewardDefinition", b =>
                {
                    b.Navigation("BundledItems");
                });

            modelBuilder.Entity("MyApi.Models.Skill", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("MyApi.Models.Achievement", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
